[versions]
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
kotlinpoet = "1.18.1"
junit = "5.11.4"
kctfork = "0.7.1"
kover = "0.9.1"
owasp-dependencycheck = "12.2.0"
mavenPublish = "0.32.0"

[libraries]
# Gradle Plugins (for build-logic)
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
maven-publish-gradlePlugin = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "mavenPublish" }

# KSP & Code Generation
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }

# Testing
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
kctfork-core = { group = "dev.zacsweers.kctfork", name = "core", version.ref = "kctfork" }
kctfork-ksp = { group = "dev.zacsweers.kctfork", name = "ksp", version.ref = "kctfork" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ci-pipelines = { id = "mappergen.ci-pipelines" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
owasp-dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "owasp-dependencycheck" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
